const headerTypes = {
    UPDATE_PRIMARYCOLOR: 'UPDATE_PRIMARYCOLOR',
    UPDATE_SLIDE: 'UPDATE_SLIDE',
    UPDATE_TITLE: 'UPDATE_TITLE',
    UPDATE_HEADER: 'UPDATE_HEADER',
    UPDATE_HEADER_FORWARD: 'UPDATE_HEADER_FORWARD',
    SWITCH_MODE: 'SWITCH_MODE',
}

export default headerTypes